version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ClothingStoreDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./ClothingStore.API
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=ClothingStoreDb;Username=postgres;Password=password"
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: